/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // tutorialSidebar: [{
  //   type: 'doc',
  //   id: 'national',
  //   label: '全國',
  // }, {
  //   type: 'category',
  //   label: '第一世代',
  //   items: ['rgby'],
  // }, {
  //   type: 'category',
  //   label: '第二世代',
  //   items: ['gsc'],
  // }, {
  //   type: 'category',
  //   label: '第三世代',
  //   items: ['rse', 'frlg'],
  // }, {
  //   type: 'category',
  //   label: '第四世代',
  //   items: ['dp', 'pt', 'hgss'],
  // }, {
  //   type: 'category',
  //   label: '第五世代',
  //   items: ['bw', 'bw2'],
  // }, {
  //   type: 'category',
  //   label: '第六世代',
  //   items: ['xy', 'oras'],
  // }, {
  //   type: 'category',
  //   label: '第七世代',
  //   items: ['sm', 'usum', 'lgpe'],
  // }, {
  //   type: 'category',
  //   label: '第八世代',
  //   items: ['swsh'],
  // }],

};

module.exports = sidebars;